### ISSUE TITLE
Moving to Gulp

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/Ocelot#107]
Talking to people here at DrupalCon LA, I feel like everyone has (or is) moving to gulp + libsass. Mostly due to performance issues with Grunt and ruby sass. I did a quick setup and it's just amazing how fast gulp and libsass work, even with browser-sync. I've got a a decent gulpfile ready, so let's see if we can move to gulp + libsass. In all my personal project, I've been using Gulp as well. 

Advantages:
- speed
- again, speed. It's soooo much faster
- not depending on this huge ruby stack and leaving bundler and rvm behind 
- pretty much any task we currently use is available for gulp as well

Disadvantages:
- scsslint is not yet ported (minor)
- new automated tool (major)

**Comment by sqndr** [comment]
This has been discussed: we will move to gulp in a future release.

**Comment by sqndr** [comment]
Once 0.1.4 is finished; I hope we can start moving towards gulp.

**Comment by rob-bar** [comment]
Yep, we will include this.
I'm gonna split this one up
