### ISSUE TITLE
Include vendor libs

### ISSUE THREAD

**Issue by klaasvw** [Crosscheck/Ocelot#111]
When including the theme in a project that compiles the assets at build time the system has to run npm install and bundle install first. Because this slows down deployments it would be better to include the vendor libs with the theme.

Note that gems are different animal than node modules. They should be installed with `bundle install --path=path/to/theme/vendor/dir` and the ruby version should be the same as the ruby version that will perform the grunt task.

**Comment by rob-bar** [comment]
I think this should be in projectify, not in this setup, what is your opinion?

**Comment by rob-bar** [comment]
Now irrelevant because we no longer use gems, I'm closing this
