### ISSUE TITLE
Realfavicon generator needs documentation

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Ocelot#122]

**Comment by sqndr** [comment]
+1 for this.

**Comment by driesd** [comment]
Just place a **favicon.png** (300 by 300px) in the **assets/img/logo/**
Then run **gulp favicons** in terminal

**You're done!**

* **Cross-device favicons** have been created in the **assets/img/favicons** folder.
* **templates/misc/favicons.tpl.php** has been created  and filled up with the correct favicon tags
* **templates/misc/favicons.tpl.php** is automatically included in the html.tpl.php's <head> section
