### ISSUE TITLE
JS: Add Settings

### ISSUE THREAD

**Issue by driesd** [Crosscheck/Ocelot#125]
settings = {
    timings: {
      speedy: 200,
      fast: 400,
      normal: 600,
      slow: 800
    },
    breakpoints: {
      mobile-landscape: 480,
      tablet-portrait: 768,
      desktop: 960,
      widescreen: 1200
    },
    debounce: {
      medium: 200
    }
  };

**Comment by sqndr** [comment]
Fixed by #126 -- for the breakpoints. In the same way, we can send timings.

**Comment by rob-bar** [comment]
Shall I close this one? or is there someone who things we are missing something here?
