### ISSUE TITLE
Importing CSS Breakpoints Into JavaScript

### ISSUE THREAD

**Issue by driesd** [Crosscheck/Ocelot#126]
https://www.lullabot.com/blog/article/importing-css-breakpoints-javascript?utm_source=dlvr.it&utm_medium=twitter

**Comment by sqndr** [comment]
This pull requests tries to do something else:
- A `ocelot.breakpoints.yml` that includes the breakpoints.
- They are passed to sass, using `node-sass-json-importer`.
- Pass the breakpoints to JS, using preprocess. 

The breakpoints are then available using: `Drupal.settings.breakpoints`
