### ISSUE TITLE
Exclude compiled CSS from the repository to avoid merge conflicts

### ISSUE THREAD

**Issue by driesd** [Crosscheck/Ocelot#128]

**Comment by rob-bar** [comment]
This task is allready done, can you close this one after verification @driesd ?

**Comment by sqndr** [comment]
Should `*.css` from /assets then be in the `.gitigore`? Or just the entire `css` folder?

**Comment by rob-bar** [comment]
related to https://github.com/Crosscheck/Jacket/issues/19
