### ISSUE TITLE
Convert variable (groups) to sass maps.

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/Ocelot#129]
`_timings.scss` contains global variables with a kinda strange name.

    $superfast: 250ms;
    $fast: 400ms;
    $normal: 700ms;
    $slow: 1000ms;

I would suggest we change this to `$timings`, a sass map.

    $timings: ('superfast': 250ms, …);

Same goes for other variable groups, such as breakpoints, …

**Comment by rob-bar** [comment]
Misschien is het een goeie conventie om de var telkens de naam van de file te geven, in dit geval correct
$timings <=> _timings.scss

**Comment by rob-bar** [comment]
Neem je ook nog de defaults en shades mee?
Das iets meer werk.
