### ISSUE TITLE
Divide the utility folder to a bower component like bamboo does

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Ocelot#157]
This is a good approach and lets us upgrade old projects with new helpers and functions.

Caution though, version managment will be tricky when upgrading the same "functions" to better "functions". This will break old sites unless they are pinned to specific versions of this bower packages, so bear in mind when making large upgrades, 
the version should be augmented in a good way say from 1.4 to 2.0.

Any ocelot related names for this new repo?
*rodent* seems ok

    Ocelots hunt over a range of 18 km2 (6.9 sq mi), taking mostly small animals, including mammals, 
    lizards, turtles, and frogs, crabs, birds, and fish.[14] Almost all of the prey that the ocelot hunts is far 
    smaller than itself, with rodents, rabbits, and opossums forming the largest part of the diet.[10] Results of 
    studies suggest that it follows and finds prey via odor trails, but the ocelot also has very good vision, 
    including night vision.

**Comment by sqndr** [comment]
+1 for semantic versioning: this means updating from 1.1 to 1.2 will always work without breaking things. Updating from 1.1 to 2 might require some additional work. In release notes, we'll have to document everything that can be "broken".

**Comment by sqndr** [comment]
I don't mind the name, we just need a separate repo. 👻

**Comment by rob-bar** [comment]
This issue depends on #121 so we will port this one to the new realease 0.2.2
When we do that we reduce the chance of errors, and we are sure everything is documented.
