### ISSUE TITLE
Upgrade Wiki

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Ocelot#184]
The wiki should be upgraded to milestone 2.1, there is still some gem and grunt stuff present.

**Comment by rob-bar** [comment]
Yes! I just made a run through the whole wiki. This is done and the documentation is up to date.
Can someone close this issue for me after checking the wiki?

I also provided the version number in the wiki, like that we have a reminder to make changes to the doc every release. I will create a new issue in 0.2.2

The wiki is actually not so well suited for doc, 
no real versions and no good ui, we should use gh-pages and jekyll an make a real site in combo with the sass doc

**Comment by sqndr** [comment]
> no real versions and no good ui, we should use gh-pages and jekyll an make a real site in combo with the sass doc

:+1:
