### ISSUE TITLE
Add gulp-autoprefixer

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/Ocelot#48]
> Autoprefixer parses CSS files and adds vendor prefixes to CSS rules using the Can I Use database to determine which prefixes are needed.

I assume some Compass snippets/mixins are now used to add vendor prefixes? Using autoprefix we could specify the browser versions we support, and let autoprefixer add prefixes if they are required for those browser versions.

- [grunt-autoprefixer](https://github.com/nDmitry/grunt-autoprefixer)
- [autoprefix on css tricks](http://css-tricks.com/autoprefixer/)

**Comment by rob-bar** [comment]
Yep, we should test something like this and see what the win is on those prefixes, and if this slows down compilation of css yes or no. 

Indeed compass does this stuff internally based on:
```scss
$browser-minimum-versions: (
  'ie': "8",
  "chrome": "20",
  "firefox": "20",
  "safari": "5",
  "opera": "22"
);
```
but you may forget to use a mixin of compass and use regular css.
This autoprefixer check should take care of the things you didn't style with compass.
So good this is a good fallback.

**Comment by rob-bar** [comment]
Thumbs up!

**Comment by sqndr** [comment]
Since we're switching to Gulp, we'll have to include the gulp task for this.

https://www.npmjs.com/package/gulp-autoprefixer

**Comment by rob-bar** [comment]
This issue is fixed, I will create a new one for the review of the browser versions 
and to see where if the prefixer really kicks in.
