### ISSUE TITLE
Vertical rhythm

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/Ocelot#50]
> Create a vertical rhythm for your site by setting the `$base-font-size` and `$base-line-height` variables and then including the establish-baseline mixin at the root of your document.

The font variables are set inside `lib/var.scss`, but a vertical rhythm is never established? 

      // Establishes baseline with Compass.
      @include establish-baseline;

      // Adjust font size to mixin. 
      // Note that those in [] are optional arguments. 
      adjust-font-size-to($to-size, [$lines], [$from-size])

      $lines = number of line heights this font is suppose to take up. 
      $from-size = current font size used to adjust to target font size.

This way, mixins like `trailing-border`,`leading-border`,`rhythm`, `margin-leader`, `margin-trailer`, `padding-leader`, `padding-trailer`, … can be used

**Comment by rob-bar** [comment]
Yes this is boilerplate! good point.

**Comment by rob-bar** [comment]
I'm attaching this to version 2.2 we now have vertical rhythm BUT, we should drop the compass function and use some component for this, whoever picks this up should first do some research on verticla rhythm libs in sass
