### ISSUE TITLE
Yeoman generator or starterkit

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/Ocelot#59]
Create a yeoman generator like https://github.com/Citrrus/Drupal-Chantilly or be compatible with the  `drush omega-wizard` command. This would avoid all the current renames you have to when *cloning* the theme repo.

**Comment by sqndr** [comment]
Closing for now … we might have to reopen later.

**Comment by rob-bar** [comment]
I'm gonna reopen this issue and put this on 2.2

**Comment by rob-bar** [comment]
This is done in https://github.com/Crosscheck/Powerplant/issues/1
