### ISSUE TITLE
Use hook_library for front-end libraries

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/Ocelot#63]
With hook_library, we can define libraries. It's also possible to add dependencies. We can add for example underscore as a library. Next we could define our custom script as a library and depend on underscore. This would make sure underscore is always loaded for our script.

=> Drupal 8 way

**Comment by sqndr** [comment]
I will implement this new way of dealing with js assets.

**Comment by rob-bar** [comment]
@sqndr Is this included in ocelot now?

**Comment by rob-bar** [comment]
If Yes, this can be closed as well
