### ISSUE TITLE
Add a basic Susy configuration

### ISSUE THREAD

**Issue by driesd** [Crosscheck/Ocelot#81]
$susy: (
  columns: 12,
  container: 960px,
  math: fluid,
  global-box-sizing: border-box
);

**Comment by cdooms** [comment]
$susy: (
flow: ltr,
math: fluid,
output: float,
gutter-position: after,
container: 1200px,
container-position: center,
columns: 12,
gutters: .25,
column-width: false,
global-box-sizing: content-box,
last-flow: to,
debug: (
image: show,
color: rgba($gray-dark, .25),
output: overlay,
toggle: top right,
),
);

**Comment by cdooms** [comment]
```scss
$susy: (
flow: ltr,
math: fluid
output: float,
gutter-position: after,
container: auto,
container-position: center,
columns: 4,
gutters: .25,
column-width: false,
global-box-sizing: content-box,
last-flow: to,
debug: (
image: hide,
color: rgba(#66f, .25),
output: background,
toggle: top right,
),
use-custom: (
background-image: true,
background-options: false,
box-sizing: true,
clearfix: false,
rem: true,
)
);
```
