### ISSUE TITLE
Package.json add postinstall script to clean out .info files

### ISSUE THREAD

**Issue by driesd** [Crosscheck/Ocelot#92]
"scripts": {
   "postinstall": "find node_modules/ -name \"*.info\" -type f -delete"
 }

**Comment by driesd** [comment]
Like this

{
 "author": "One Agency",
 "name": "kotk_omega",
 "version": "0.0.1",
 "dependencies": {},
 "devDependencies": {
   "grunt": "~0.4.1",
   "grunt-contrib-compass": "*",
   "grunt-contrib-coffee": "*",
   "grunt-contrib-jshint": "*",
   "grunt-contrib-concat": "*",
   "grunt-contrib-uglify": "*",
   "grunt-contrib-watch": "*",
   "grunt-contrib-imagemin": "*",
   "grunt-scss-lint": "*",
   "matchdep": "*"
 },
 "engines": {
   "node": ">=0.8.0"
 },
 "scripts": {
   "postinstall": "find node_modules/ -name \"*.info\" -type f -delete"
 }
}

**Comment by rob-bar** [comment]
Deze ga ik sluiten omdat die er al inzit.
